---
# tasks file for systemd
- name: systemd-resolved
  ansible.builtin.template:
    dest: /etc/systemd/resolved.conf
    src: etc/systemd/resolved.conf.j2
  notify:
    - Restart systemd-resolved.service

- name: systemd-networkd
  ansible.builtin.template:
    dest: /etc/systemd/networkd.conf
    src: etc/systemd/networkd.conf.j2
  notify:
    - Restart systemd-networkd.service
