---
# tasks file for systemd
- name: systemd-resolved
  ansible.builtin.template:
    dest: /etc/systemd/resolved.conf
    src: etc/systemd/resolved.conf.j2
  notify:
    - Restart systemd-resolved.service

- name: /etc/systemd/network/10-netplan-{{ item.interface }}.network.d
  ansible.builtin.file:
    path: /etc/systemd/network/10-netplan-{{ item.interface }}.network.d
    state: directory
  loop: "{{ systemd_multicastDNS }}"
- name: mDNS
  ansible.builtin.copy:
    dest: /etc/systemd/network/10-netplan-{{ item.interface }}.network.d/mDNS.conf
    content: |
      [Network]
      MulticastDNS={{ item.state | lower }}
  notify:
    - Restart systemd-networkd.service
  loop: "{{ systemd_multicastDNS }}"

