---
# handlers file for systemd
#
- name: Restart systemd-resolved.service
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted

- name: Restart systemd-networkd.service
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: restarted
